# Generated by Django 5.2.9 on 2026-03-11 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailImportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email_address', models.EmailField(max_length=254, verbose_name='E-Mail Adresse')),
                ('protocol', models.CharField(choices=[('IMAP', 'IMAP'), ('POP3', 'POP3')], default='IMAP', max_length=10, verbose_name='Protokoll')),
                ('imap_server', models.CharField(max_length=200, verbose_name='IMAP Server')),
                ('imap_port', models.IntegerField(default=993, verbose_name='IMAP Port')),
                ('smtp_server', models.CharField(blank=True, max_length=200, verbose_name='SMTP Server')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='SMTP Port')),
                ('username', models.CharField(max_length=200, verbose_name='Benutzername')),
                ('password', models.CharField(max_length=500, verbose_name='Passwort')),
                ('use_ssl', models.BooleanField(default=True, verbose_name='SSL verwenden')),
                ('mailbox', models.CharField(default='INBOX', max_length=100, verbose_name='Mailbox')),
                ('check_frequency', models.IntegerField(default=15, verbose_name='Prüf-Frequenz (Minuten)')),
                ('delete_after_import', models.BooleanField(default=False, verbose_name='Nach Import löschen')),
                ('process_attachments', models.BooleanField(default=True, verbose_name='Anhänge verarbeiten')),
                ('attachment_types', models.JSONField(default=list, verbose_name='Anhang-Typen')),
                ('keywords', models.JSONField(default=list, verbose_name='Such-Keywords')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('last_check', models.DateTimeField(blank=True, null=True, verbose_name='Letzte Prüfung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'E-Mail Import Konfiguration',
                'verbose_name_plural': 'E-Mail Import Konfigurationen',
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.CharField(max_length=500, unique=True, verbose_name='Message-ID')),
                ('subject', models.CharField(blank=True, max_length=1000, verbose_name='Betreff')),
                ('from_email', models.EmailField(max_length=254, verbose_name='Absender')),
                ('to_email', models.EmailField(max_length=254, verbose_name='Empfänger')),
                ('cc', models.TextField(blank=True, verbose_name='CC')),
                ('bcc', models.TextField(blank=True, verbose_name='BCC')),
                ('body_plain', models.TextField(blank=True, verbose_name='Text-Inhalt')),
                ('body_html', models.TextField(blank=True, verbose_name='HTML-Inhalt')),
                ('received_date', models.DateTimeField(verbose_name='Empfangsdatum')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='Sendedatum')),
                ('size', models.IntegerField(default=0, verbose_name='Größe (Bytes)')),
                ('has_attachments', models.BooleanField(default=False, verbose_name='Hat Anhänge')),
                ('attachment_count', models.IntegerField(default=0, verbose_name='Anzahl Anhänge')),
                ('attachment_info', models.JSONField(default=list, verbose_name='Anhang-Informationen')),
                ('status', models.CharField(choices=[('NEW', 'Neu'), ('PROCESSING', 'In Verarbeitung'), ('PROCESSED', 'Verarbeitet'), ('ERROR', 'Fehler'), ('ARCHIVED', 'Archiviert')], default='NEW', max_length=20, verbose_name='Status')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Verarbeitet am')),
                ('error_message', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('raw_headers', models.TextField(blank=True, verbose_name='Raw Headers')),
                ('raw_body', models.TextField(blank=True, verbose_name='Raw Body')),
                ('tags', models.JSONField(default=list, verbose_name='Tags')),
                ('intake_rawinput_id', models.UUIDField(blank=True, null=True, verbose_name='Intake RawInput ID')),
                ('config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest_email.emailimportconfig', verbose_name='Import Konfiguration')),
            ],
            options={
                'verbose_name': 'E-Mail Nachricht',
                'verbose_name_plural': 'E-Mail Nachrichten',
                'ordering': ['-received_date'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=500, verbose_name='Dateiname')),
                ('content_type', models.CharField(max_length=200, verbose_name='Content-Type')),
                ('size', models.IntegerField(verbose_name='Größe (Bytes)')),
                ('file_path', models.CharField(blank=True, max_length=1000, verbose_name='Dateipfad')),
                ('storage_backend', models.CharField(default='local', max_length=100, verbose_name='Storage Backend')),
                ('content_text', models.TextField(blank=True, verbose_name='Extrahiertes Text')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Verarbeitet')),
                ('processing_error', models.TextField(blank=True, verbose_name='Verarbeitungsfehler')),
                ('metadata', models.JSONField(default=dict, verbose_name='Metadaten')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ingest_email.emailmessage', verbose_name='E-Mail')),
            ],
            options={
                'verbose_name': 'E-Mail Anhang',
                'verbose_name_plural': 'E-Mail Anhänge',
            },
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['message_id'], name='ingest_emai_message_5a60da_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['from_email'], name='ingest_emai_from_em_c06a01_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['received_date'], name='ingest_emai_receive_9ef24c_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['status'], name='ingest_emai_status_1f0fd7_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['intake_rawinput_id'], name='ingest_emai_intake__dbbaec_idx'),
        ),
        migrations.AddIndex(
            model_name='emailattachment',
            index=models.Index(fields=['email'], name='ingest_emai_email_i_6a5e35_idx'),
        ),
        migrations.AddIndex(
            model_name='emailattachment',
            index=models.Index(fields=['content_type'], name='ingest_emai_content_fcc34f_idx'),
        ),
    ]
