# Generated by Django 5.2.9 on 2026-06-29 14:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DmsDocType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Stabiler Schlüssel, z. B. 'vertrag', 'rechnung'.", max_length=64, unique=True)),
                ('label', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('retention_years', models.PositiveIntegerField(blank=True, help_text='Gesetzliche Mindest-Aufbewahrung in Jahren. Leer = unbegrenzt/keine.', null=True)),
                ('delete_after_days', models.PositiveIntegerField(blank=True, help_text='Gnadenfrist nach Fristablauf, bevor endgültig löschbar.', null=True)),
                ('default_volume', models.CharField(choices=[('office', 'O: office (Geschäftsdokumente)'), ('public', 'X: public (CVs / Profile)')], default='office', max_length=8)),
                ('path_template', models.CharField(blank=True, help_text="Pfad-Template unter der abpe/-Wurzel, z. B. '{owner_bucket}/{owner_slug}/Vertraege'.", max_length=255)),
                ('icon_class', models.CharField(blank=True, help_text="CSS-Klasse für das Datei-Icon, z. B. 'crm-doc-contract'.", max_length=64)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_system', models.BooleanField(default=False, help_text='Systemtyp — vor Löschen geschützt.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DMS-Dokumenttyp',
                'verbose_name_plural': 'DMS-Dokumenttypen',
                'ordering': ('sort_order', 'label'),
            },
        ),
        migrations.CreateModel(
            name='DmsMetadataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=128)),
                ('default', models.CharField(blank=True, max_length=255)),
                ('validation', models.CharField(blank=True, help_text='Optionaler Validierungs-Backend (Dotted-Path).', max_length=128)),
                ('parser', models.CharField(blank=True, max_length=128)),
                ('help_text', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'DMS-Metadatentyp',
                'verbose_name_plural': 'DMS-Metadatentypen',
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='DmsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('color', models.CharField(default='#163258', max_length=16)),
                ('is_inbox_tag', models.BooleanField(default=False, help_text='Markiert frisch eingegangene, noch nicht abgelegte Dokumente.')),
                ('is_system', models.BooleanField(default=False)),
                ('match', models.CharField(blank=True, max_length=256)),
                ('matching_algorithm', models.PositiveSmallIntegerField(choices=[(0, 'Keine'), (1, 'Irgendein Wort'), (2, 'Alle Wörter'), (3, 'Exakte Zeichenkette'), (4, 'Regulärer Ausdruck'), (5, 'Unscharf'), (6, 'Auto (KI / Deepseek)')], default=0)),
                ('is_insensitive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'DMS-Tag',
                'verbose_name_plural': 'DMS-Tags',
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='DmsGewerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nummer', models.CharField(help_text='Gewerk-/Projektnummer.', max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('account_crm_id', models.CharField(db_index=True, help_text='Kunde (CrmAccount.crm_id).', max_length=64)),
                ('status', models.CharField(choices=[('aktiv', 'Aktiv'), ('pausiert', 'Pausiert'), ('abgeschlossen', 'Abgeschlossen')], default='aktiv', max_length=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gewerk',
                'verbose_name_plural': 'Gewerke',
                'ordering': ('-start_date', 'nummer'),
                'indexes': [models.Index(fields=['account_crm_id'], name='idx_gewerk_account'), models.Index(fields=['status'], name='idx_gewerk_status')],
            },
        ),
        migrations.CreateModel(
            name='DmsArbeitspaket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="z. B. 'AP1'.", max_length=32)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, help_text="z. B. 'Tag', 'Stück'.", max_length=32)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('gewerk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbeitspakete', to='abpe_edms.dmsgewerk')),
            ],
            options={
                'verbose_name': 'Arbeitspaket',
                'verbose_name_plural': 'Arbeitspakete',
                'ordering': ('gewerk', 'sort_order', 'key'),
            },
        ),
        migrations.CreateModel(
            name='CrmDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('direction', models.CharField(choices=[('keine', '—'), ('eingang', 'Eingang (von Berater an abcona)'), ('ausgang', 'Ausgang (von abcona an Kunde)')], default='keine', max_length=8)),
                ('document_date', models.DateField(blank=True, help_text='Dokumentdatum — Anker für die Aufbewahrungsberechnung.', null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, help_text='Geschäfts-Gültigkeit (z. B. Vertragsende).', null=True)),
                ('retention_years_override', models.PositiveIntegerField(blank=True, help_text='Übersteuert die DocType-Frist für dieses eine Dokument.', null=True)),
                ('retention_until', models.DateField(blank=True, db_index=True, help_text='Berechnetes Ende der Aufbewahrungspflicht (Jahresende).', null=True)),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('gueltig', 'Gültig'), ('abgelaufen', 'Abgelaufen (Gültigkeit)'), ('archiviert', 'Archiviert')], default='gueltig', max_length=16)),
                ('is_stub', models.BooleanField(default=False, help_text='Platzhalter für angefordertes, noch fehlendes Dok.')),
                ('needs_review', models.BooleanField(db_index=True, default=False, help_text='Im Posteingang — noch nicht final zugeordnet.')),
                ('in_trash', models.BooleanField(db_index=True, default=False)),
                ('trashed_at', models.DateTimeField(blank=True, null=True)),
                ('trashed_reason', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('generiert', 'Generiert (studio_doc)'), ('hochgeladen', 'Hochgeladen (Web)'), ('gescannt', 'Gescannt (Samba-Sync)'), ('email', 'Per E-Mail (Posteingang)')], default='hochgeladen', max_length=16)),
                ('language', models.CharField(default='de', max_length=8)),
                ('content', models.TextField(blank=True, help_text='Extrahierter/OCR-Text — Quelle für den Elasticsearch-Index.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trashed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doctype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='abpe_edms.dmsdoctype')),
                ('gewerk', models.ForeignKey(blank=True, help_text='Optional — gruppiert Leistungsnachweise & Rechnungen.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='abpe_edms.dmsgewerk')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumente',
                'ordering': ('-document_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='DmsGewerkBerater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_crm_id', models.CharField(db_index=True, help_text='Berater (CrmContact.crm_id).', max_length=64)),
                ('role', models.CharField(blank=True, max_length=64)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('gewerk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='berater', to='abpe_edms.dmsgewerk')),
            ],
            options={
                'verbose_name': 'Gewerk-Berater',
                'verbose_name_plural': 'Gewerk-Berater',
            },
        ),
        migrations.CreateModel(
            name='DmsLeistungsposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('keine', '—'), ('eingang', 'Eingang (von Berater an abcona)'), ('ausgang', 'Ausgang (von abcona an Kunde)')], default='keine', help_text='Eingang (Berater->abcona) oder Ausgang (abcona->Kunde).', max_length=8)),
                ('owner_crm_id', models.CharField(blank=True, db_index=True, help_text='Berater der Eingangs-Position (für Summen je Berater).', max_length=64)),
                ('beschreibung', models.CharField(blank=True, max_length=512)),
                ('menge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('einheit', models.CharField(blank=True, max_length=32)),
                ('einzelpreis', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('betrag', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arbeitspaket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positionen', to='abpe_edms.dmsarbeitspaket')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionen', to='abpe_edms.crmdocument')),
            ],
            options={
                'verbose_name': 'Leistungsposition',
                'verbose_name_plural': 'Leistungspositionen',
            },
        ),
        migrations.CreateModel(
            name='DmsDocumentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=512)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='abpe_edms.crmdocument')),
                ('metadata_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='abpe_edms.dmsmetadatatype')),
            ],
            options={
                'verbose_name': 'Dokument-Metadatum',
                'verbose_name_plural': 'Dokument-Metadaten',
            },
        ),
        migrations.CreateModel(
            name='DmsDocTypeMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_fields', to='abpe_edms.dmsdoctype')),
                ('metadata_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctype_links', to='abpe_edms.dmsmetadatatype')),
            ],
            options={
                'verbose_name': 'DocType-Metadatenfeld',
                'verbose_name_plural': 'DocType-Metadatenfelder',
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='DmsSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('volume', models.CharField(blank=True, choices=[('office', 'O: office (Geschäftsdokumente)'), ('public', 'X: public (CVs / Profile)')], max_length=8, null=True)),
                ('files_seen', models.PositiveIntegerField(default=0)),
                ('files_new', models.PositiveIntegerField(default=0)),
                ('files_updated', models.PositiveIntegerField(default=0)),
                ('files_removed', models.PositiveIntegerField(default=0)),
                ('documents_indexed', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('laeuft', 'Läuft'), ('ok', 'OK'), ('fehler', 'Fehler')], default='laeuft', max_length=8)),
                ('triggered_by', models.CharField(choices=[('cron', 'Zeitplan'), ('manuell', 'Manuell')], default='cron', max_length=8)),
                ('message', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sync-Lauf',
                'verbose_name_plural': 'Sync-Läufe',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='DmsDocumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abpe_edms.crmdocument')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abpe_edms.dmstag')),
            ],
        ),
        migrations.AddField(
            model_name='crmdocument',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', through='abpe_edms.DmsDocumentTag', to='abpe_edms.dmstag'),
        ),
        migrations.CreateModel(
            name='CrmDocumentOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_crm_id', models.CharField(db_index=True, max_length=64)),
                ('owner_type', models.CharField(choices=[('contact', 'Berater (CrmContact)'), ('account', 'Kunde (CrmAccount)')], max_length=8)),
                ('role', models.CharField(choices=[('primaer', 'Primärer Eigentümer'), ('geteilt', 'Geteilt (mehrere Berater)'), ('kunde', 'Kunde / Auftraggeber'), ('kopie', 'Nur Kopie / Kenntnis')], default='primaer', max_length=16)),
                ('is_primary', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='abpe_edms.crmdocument')),
            ],
            options={
                'verbose_name': 'Dokument-Eigentümer',
                'verbose_name_plural': 'Dokument-Eigentümer',
                'indexes': [models.Index(fields=['owner_crm_id', 'owner_type'], name='idx_owner_lookup')],
                'constraints': [models.UniqueConstraint(fields=('document', 'owner_crm_id', 'owner_type'), name='uq_document_owner')],
            },
        ),
        migrations.CreateModel(
            name='CrmDocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('volume', models.CharField(choices=[('office', 'O: office (Geschäftsdokumente)'), ('public', 'X: public (CVs / Profile)')], max_length=8)),
                ('relative_path', models.CharField(help_text='Pfad innerhalb des Shares — maßgeblich für den Datei-Zugriff.', max_length=1024)),
                ('filename', models.CharField(help_text='Dateiname — behält Original-/Erzeuger-Name (vgl. CrmCallRecording).', max_length=512)),
                ('mimetype', models.CharField(blank=True, max_length=128)),
                ('encoding', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, db_index=True, help_text='Hash der Datei — Dedup & Integritätsprüfung.', max_length=128)),
                ('checksum_algo', models.CharField(default='sha256', max_length=16)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('in_trash', models.BooleanField(default=False)),
                ('trashed_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, help_text="Grund/Notiz, z. B. 'ersetzt durch v3'.", max_length=255)),
                ('source_path_original', models.CharField(blank=True, help_text='Ursprünglicher Fundort beim Samba-Scan (Abgleich/Reconcile).', max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='abpe_edms.crmdocument')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='abpe_edms.crmdocumentversion')),
            ],
            options={
                'verbose_name': 'Dokument-Version',
                'verbose_name_plural': 'Dokument-Versionen',
                'ordering': ('document', '-version_no'),
                'indexes': [models.Index(fields=['volume', 'relative_path'], name='idx_version_path')],
                'constraints': [models.UniqueConstraint(fields=('document', 'version_no'), name='uq_document_version')],
            },
        ),
        migrations.CreateModel(
            name='DmsDocumentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_uuid', models.UUIDField(blank=True, help_text='Bewahrt die Referenz auch nach endgültigem Löschen.', null=True)),
                ('event_type', models.CharField(choices=[('erstellt', 'Erstellt'), ('version_neu', 'Neue Version'), ('verschoben', 'Verschoben / umbenannt'), ('klassifiziert', 'Klassifiziert'), ('owner_geaendert', 'Owner geändert'), ('metadaten', 'Metadaten geändert'), ('archiviert', 'Archiviert (Papierkorb)'), ('wiederhergestellt', 'Wiederhergestellt'), ('endgueltig_geloescht', 'Endgültig gelöscht')], max_length=24)),
                ('actor_label', models.CharField(blank=True, help_text="Z. B. 'scanner', 'cron', 'deepseek'.", max_length=64)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='abpe_edms.crmdocument')),
            ],
            options={
                'verbose_name': 'Dokument-Ereignis',
                'verbose_name_plural': 'Dokument-Ereignisse',
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['event_type'], name='idx_event_type')],
            },
        ),
        migrations.CreateModel(
            name='DmsDocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('bezieht_sich_auf', 'Bezieht sich auf'), ('rechnung_zu_leistung', 'Rechnung ↔ Leistungsnachweis'), ('ersetzt', 'Ersetzt'), ('anlage_zu', 'Anlage zu')], default='bezieht_sich_auf', max_length=24)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_out', to='abpe_edms.crmdocument')),
                ('target_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_in', to='abpe_edms.crmdocument')),
            ],
            options={
                'verbose_name': 'Dokument-Verknüpfung',
                'verbose_name_plural': 'Dokument-Verknüpfungen',
                'constraints': [models.UniqueConstraint(fields=('source_document', 'target_document', 'link_type'), name='uq_document_link')],
            },
        ),
        migrations.AddConstraint(
            model_name='dmsarbeitspaket',
            constraint=models.UniqueConstraint(fields=('gewerk', 'key'), name='uq_gewerk_arbeitspaket'),
        ),
        migrations.AddConstraint(
            model_name='dmsgewerkberater',
            constraint=models.UniqueConstraint(fields=('gewerk', 'contact_crm_id'), name='uq_gewerk_berater'),
        ),
        migrations.AddIndex(
            model_name='dmsleistungsposition',
            index=models.Index(fields=['direction'], name='idx_pos_direction'),
        ),
        migrations.AddIndex(
            model_name='dmsleistungsposition',
            index=models.Index(fields=['arbeitspaket'], name='idx_pos_ap'),
        ),
        migrations.AddConstraint(
            model_name='dmsdocumentmetadata',
            constraint=models.UniqueConstraint(fields=('document', 'metadata_type'), name='uq_document_metadata'),
        ),
        migrations.AddConstraint(
            model_name='dmsdoctypemetadata',
            constraint=models.UniqueConstraint(fields=('doctype', 'metadata_type'), name='uq_doctype_metadata'),
        ),
        migrations.AddConstraint(
            model_name='dmsdocumenttag',
            constraint=models.UniqueConstraint(fields=('document', 'tag'), name='uq_document_tag'),
        ),
        migrations.AddIndex(
            model_name='crmdocument',
            index=models.Index(fields=['doctype'], name='idx_doc_doctype'),
        ),
        migrations.AddIndex(
            model_name='crmdocument',
            index=models.Index(fields=['gewerk'], name='idx_doc_gewerk'),
        ),
        migrations.AddIndex(
            model_name='crmdocument',
            index=models.Index(fields=['direction'], name='idx_doc_direction'),
        ),
        migrations.AddIndex(
            model_name='crmdocument',
            index=models.Index(fields=['in_trash', 'needs_review'], name='idx_doc_state'),
        ),
        migrations.AddIndex(
            model_name='crmdocument',
            index=models.Index(fields=['retention_until'], name='idx_doc_retention'),
        ),
        migrations.AddIndex(
            model_name='crmdocument',
            index=models.Index(fields=['document_date'], name='idx_doc_date'),
        ),
    ]
