# Generated by Django 5.2.9 on 2026-07-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_edms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmdocumentowner',
            name='is_suggestion',
            field=models.BooleanField(db_index=True, default=False, help_text='Unsicherer Match — muss bestätigt werden'),
        ),
        migrations.AddField(
            model_name='crmdocumentowner',
            name='match_source',
            field=models.CharField(blank=True, default='', help_text='Wie der Match kam (exact/normalized/substring/path/manual)', max_length=16),
        ),
    ]
