# Generated by Django 5.2.9 on 2026-05-18 10:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSenderAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-Mail Adresse')),
                ('display_name', models.CharField(help_text='z.B. "abcona e. K. Vertrieb"', max_length=200, verbose_name='Anzeigename')),
                ('sender_mode', models.CharField(choices=[('USER', 'User (From = eingeloggter User)'), ('TEMPLATE', 'Template (feste Adresse)'), ('AUTO', 'Auto (maschinell / noreply)')], default='TEMPLATE', max_length=20, verbose_name='Absender-Modus')),
                ('is_default', models.BooleanField(default=False, verbose_name='Standard-Absender')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Absender-Konto',
                'verbose_name_plural': 'Absender-Konten',
                'ordering': ['-is_default', 'email'],
            },
        ),
        migrations.CreateModel(
            name='EmailSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('identifier', models.SlugField(max_length=100, unique=True, verbose_name='Technischer Name')),
                ('html_body', models.TextField(help_text='HTML-Signatur mit {variablen}', verbose_name='HTML Signatur')),
                ('text_body', models.TextField(blank=True, help_text='Plaintext Fallback', verbose_name='Text Signatur')),
                ('is_default', models.BooleanField(default=False, verbose_name='Standard-Signatur')),
                ('is_public', models.BooleanField(default=False, help_text='Sichtbar für alle User', verbose_name='Öffentliche Signatur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('sender_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='abpe_email_studio.emailsenderaccount', verbose_name='Zugeordnetes Absender-Konto')),
            ],
            options={
                'verbose_name': 'Signatur',
                'verbose_name_plural': 'Signaturen',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.SlugField(help_text='Für API: EmailStudio.send(template="cv_generated_berater")', max_length=200, unique=True, verbose_name='Technischer Name')),
                ('name', models.CharField(max_length=200, verbose_name='Anzeigename')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('app_scope', models.CharField(choices=[('intake', 'Intake / CV Upload'), ('matching', 'Matching'), ('workflow', 'Workflow'), ('portal', 'Portal / System'), ('general', 'Allgemein'), ('system', 'System / Auto')], default='general', max_length=50, verbose_name='App-Bereich')),
                ('event_type', models.CharField(default='general', help_text='z.B. cv_generated, match_found', max_length=100, verbose_name='Event-Typ')),
                ('sender_mode', models.CharField(choices=[('USER', 'User (From = eingeloggter User)'), ('TEMPLATE', 'Template (feste Adresse)'), ('AUTO', 'Auto (maschinell / noreply)')], default='TEMPLATE', max_length=20, verbose_name='Absender-Modus')),
                ('cc_emails', models.TextField(blank=True, help_text='Komma-getrennt', verbose_name='CC')),
                ('bcc_emails', models.TextField(blank=True, help_text='Komma-getrennt', verbose_name='BCC')),
                ('subject', models.CharField(help_text='Kann {variablen} enthalten', max_length=500, verbose_name='Betreff')),
                ('html_body', models.TextField(verbose_name='HTML Body')),
                ('text_body', models.TextField(blank=True, help_text='Plaintext für Mail-Clients ohne HTML', verbose_name='Text Fallback')),
                ('variables', models.JSONField(blank=True, default=list, help_text='[{"name": "name", "type": "string", "source": "context", "required": true}]', verbose_name='Variablen')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktiv'), ('DRAFT', 'Entwurf'), ('ARCHIVE', 'Archiv')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('active_version', models.PositiveIntegerField(default=1, verbose_name='Aktive Version')),
                ('include_signature', models.BooleanField(default=True, verbose_name='Signatur anhängen')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Verwendungen')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt verwendet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('sender_account', models.ForeignKey(blank=True, help_text='Nur relevant bei Modus TEMPLATE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='abpe_email_studio.emailsenderaccount', verbose_name='Absender-Konto')),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='abpe_email_studio.emailsignature', verbose_name='Signatur')),
            ],
            options={
                'verbose_name': 'E-Mail Vorlage',
                'verbose_name_plural': 'E-Mail Vorlagen',
                'ordering': ['app_scope', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('queue_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_emails', models.JSONField(default=list, verbose_name='Empfänger')),
                ('cc_emails', models.JSONField(default=list, verbose_name='CC')),
                ('bcc_emails', models.JSONField(default=list, verbose_name='BCC')),
                ('variables', models.JSONField(default=dict, verbose_name='Variablen')),
                ('sender_mode', models.CharField(choices=[('USER', 'User (From = eingeloggter User)'), ('TEMPLATE', 'Template (feste Adresse)'), ('AUTO', 'Auto (maschinell / noreply)')], default='TEMPLATE', max_length=20)),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='User ID (für User-Modus)')),
                ('task_reference', models.CharField(blank=True, max_length=200)),
                ('app_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Ausstehend'), ('RUNNING', 'Läuft'), ('DONE', 'Erledigt'), ('FAILED', 'Fehlgeschlagen'), ('CANCELLED', 'Abgebrochen')], default='PENDING', max_length=20, verbose_name='Status')),
                ('celery_task_id', models.CharField(blank=True, max_length=200, verbose_name='Celery Task ID')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='Versuche')),
                ('max_retries', models.PositiveSmallIntegerField(default=3, verbose_name='Max Versuche')),
                ('error_message', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Geplant für')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Verarbeitet am')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='abpe_email_studio.emailtemplate', verbose_name='Vorlage')),
            ],
            options={
                'verbose_name': 'E-Mail Warteschlange',
                'verbose_name_plural': 'E-Mail Warteschlange',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='Template Version')),
                ('from_email', models.EmailField(max_length=254, verbose_name='Von')),
                ('from_name', models.CharField(blank=True, max_length=200, verbose_name='Von Name')),
                ('sender_mode', models.CharField(choices=[('USER', 'User (From = eingeloggter User)'), ('TEMPLATE', 'Template (feste Adresse)'), ('AUTO', 'Auto (maschinell / noreply)')], default='TEMPLATE', max_length=20, verbose_name='Absender-Modus')),
                ('to_emails', models.JSONField(default=list, verbose_name='An')),
                ('cc_emails', models.JSONField(default=list, verbose_name='CC')),
                ('bcc_emails', models.JSONField(default=list, verbose_name='BCC')),
                ('reply_to', models.EmailField(blank=True, max_length=254, verbose_name='Reply-To')),
                ('subject', models.CharField(max_length=500, verbose_name='Betreff')),
                ('html_body', models.TextField(blank=True, verbose_name='HTML Body')),
                ('text_body', models.TextField(blank=True, verbose_name='Text Body')),
                ('variables_used', models.JSONField(blank=True, default=dict, verbose_name='Verwendete Variablen')),
                ('status', models.CharField(choices=[('OK', 'Erfolgreich'), ('FAILED', 'Fehlgeschlagen'), ('QUEUED', 'In Warteschlange'), ('SENDING', 'Wird gesendet')], default='OK', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('task_reference', models.CharField(blank=True, help_text='z.B. TASK-2026-00123 oder AID-12345', max_length=200, verbose_name='Task Referenz')),
                ('app_reference', models.CharField(blank=True, help_text='Welche App hat gesendet', max_length=100, verbose_name='App Referenz')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Gesendet am')),
                ('sent_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL, verbose_name='Gesendet von User')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='abpe_email_studio.emailtemplate', verbose_name='Vorlage')),
            ],
            options={
                'verbose_name': 'E-Mail Log',
                'verbose_name_plural': 'E-Mail Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='Version')),
                ('subject', models.CharField(max_length=500)),
                ('html_body', models.TextField()),
                ('text_body', models.TextField(blank=True)),
                ('variables', models.JSONField(default=list)),
                ('sender_mode', models.CharField(choices=[('USER', 'User (From = eingeloggter User)'), ('TEMPLATE', 'Template (feste Adresse)'), ('AUTO', 'Auto (maschinell / noreply)')], default='TEMPLATE', max_length=20)),
                ('change_note', models.CharField(blank=True, max_length=500, verbose_name='Änderungsnotiz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Gespeichert von')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='abpe_email_studio.emailtemplate', verbose_name='Vorlage')),
            ],
            options={
                'verbose_name': 'Template Version',
                'verbose_name_plural': 'Template Versionen',
                'ordering': ['-version'],
            },
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['identifier'], name='abpe_email__identif_7dbec5_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['app_scope', 'event_type'], name='abpe_email__app_sco_0071bc_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['status'], name='abpe_email__status_88c64a_idx'),
        ),
        migrations.AddIndex(
            model_name='emailqueue',
            index=models.Index(fields=['status', 'created_at'], name='abpe_email__status_575575_idx'),
        ),
        migrations.AddIndex(
            model_name='emailqueue',
            index=models.Index(fields=['celery_task_id'], name='abpe_email__celery__d03b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['status', 'sent_at'], name='abpe_email__status_efd9c3_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['from_email', 'sent_at'], name='abpe_email__from_em_927d87_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['task_reference'], name='abpe_email__task_re_854853_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['app_reference'], name='abpe_email__app_ref_4b91d8_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['sent_by_user', 'sent_at'], name='abpe_email__sent_by_507e27_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplateversion',
            unique_together={('template', 'version')},
        ),
    ]
