# Generated by Django 5.2.9 on 2026-05-18 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_email_studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplateTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(help_text='ISO-Code z.B. en, fr, it', max_length=10, verbose_name='Sprache')),
                ('subject', models.CharField(max_length=500, verbose_name='Betreff')),
                ('html_body', models.TextField(verbose_name='HTML Body')),
                ('text_body', models.TextField(blank=True, verbose_name='Text Body')),
                ('auto_translated', models.BooleanField(default=True, verbose_name='Auto-übersetzt')),
                ('translated_at', models.DateTimeField(auto_now=True, verbose_name='Übersetzt am')),
                ('reviewed', models.BooleanField(default=False, verbose_name='Geprüft')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='abpe_email_studio.emailtemplate', verbose_name='Vorlage')),
            ],
            options={
                'verbose_name': 'Template Übersetzung',
                'verbose_name_plural': 'Template Übersetzungen',
                'ordering': ['lang'],
                'unique_together': {('template', 'lang')},
            },
        ),
    ]
