# Generated by Django 5.2.9 on 2026-05-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_email_studio', '0002_emailtemplatetranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='translation_languages',
            field=models.JSONField(blank=True, default=list, help_text='z.B. ["en", "fr"] — DE ist immer Referenz', verbose_name='Übersetzungssprachen'),
        ),
    ]
