# Generated by Django 5.2.9 on 2026-05-18 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_email_studio', '0003_emailtemplate_translation_languages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.SlugField(max_length=100, unique=True, verbose_name='Technischer Name')),
                ('name', models.CharField(max_length=200, verbose_name='Anzeigename')),
                ('module_type', models.CharField(choices=[('HEADER', 'Header'), ('FOOTER', 'Footer'), ('SIGNATURE', 'Signatur'), ('BUTTON', 'Button / CTA'), ('SECTION', 'Inhaltsbereich'), ('DISCLAIMER', 'Disclaimer')], default='SECTION', max_length=20, verbose_name='Typ')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('html_body', models.TextField(help_text='Kann {variablen} enthalten', verbose_name='HTML Block')),
                ('text_body', models.TextField(blank=True, help_text='Plaintext Fallback', verbose_name='Text Block')),
                ('preview_bg', models.CharField(default='#ffffff', max_length=20, verbose_name='Vorschau Hintergrund')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'E-Mail Modul',
                'verbose_name_plural': 'E-Mail Module',
                'ordering': ['module_type', 'name'],
            },
        ),
    ]
