# Generated by Django 5.2.9 on 2026-05-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_email_studio', '0004_emailmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='signature_mode',
            field=models.CharField(choices=[('NONE', 'Keine Signatur'), ('TEAM', 'Allgemein — abcona Team'), ('USER', 'User des Absenders'), ('FIXED', 'Feste Signatur wählen'), ('DYNAMIC', 'Beim Versand wählbar')], default='USER', help_text='Steuert welche Signatur beim Versand angehängt wird', max_length=20, verbose_name='Signatur-Modus'),
        ),
        migrations.AddField(
            model_name='emailtemplateversion',
            name='is_milestone',
            field=models.BooleanField(default=False, help_text='Vom User manuell gesetzter Merke-Stand', verbose_name='Meilenstein'),
        ),
        migrations.AddField(
            model_name='emailtemplateversion',
            name='milestone_label',
            field=models.CharField(blank=True, help_text='z.B. "vor Farb-Test"', max_length=200, verbose_name='Meilenstein-Bezeichnung'),
        ),
    ]
