# Generated by Django 5.2.9 on 2026-07-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_email_studio', '0005_add_signature_mode_and_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='app_scope',
            field=models.CharField(choices=[('intake', 'Intake / CV Upload'), ('matching', 'Matching'), ('workflow', 'Workflow'), ('telefon', 'Telefon / PBX'), ('portal', 'Portal / System'), ('general', 'Allgemein'), ('system', 'System / Auto')], default='general', max_length=50, verbose_name='App-Bereich'),
        ),
    ]
