# Generated by Django 5.2.9 on 2026-07-14 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_email_studio', '0006_add_appscope_telefon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('app_scope', models.CharField(choices=[('general', 'Allgemein'), ('meetme', 'MeetMe'), ('matching', 'Matching'), ('pbx', 'PBX / Telefon'), ('crm', 'CRM')], default='general', max_length=32)),
                ('system', models.TextField(help_text='System-Prompt für DeepSeek')),
                ('user_template', models.TextField(help_text='User-Template mit [[INSTRUCTION]], [[TEXT]], [[NOTES]], …')),
                ('instruction_default', models.TextField(blank=True, help_text='Standard-Instruction wenn API keine übergibt (z.B. meetme_email)')),
                ('aktiv', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_prompts_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KI-Prompt',
                'verbose_name_plural': 'KI-Prompts',
                'db_table': 'abpe_email_studio_ai_prompt',
                'ordering': ['app_scope', 'name'],
            },
        ),
    ]
