"""ErgebnisTyp-Katalog — Seed-Daten (codes stabil, UUIDs via get_or_create)."""

# kontext-Werte laut Architektur Kap. 2.3
ERGEBNIS_TYPEN = [
    {
        'code': 'angebot_angenommen',
        'label': 'Angebot angenommen',
        'label_i18n_key': 'sh.erg_angebot_angenommen',
        'kontext': 'kunde_angebot',
        'wirkung_status': 'vermittelt',
        'eingabefelder': [],
        'zeigt_dialog': False,
        'schliesst_vorgang': False,
        'sort_order': 10,
        'fx_labels': ['Kanban: Berater → Vermittelt', 'Folgeaufgabe laut Regel', 'Historie-Eintrag'],
    },
    {
        'code': 'in_pruefung',
        'label': 'In Prüfung',
        'label_i18n_key': 'sh.erg_in_pruefung',
        'kontext': 'kunde_angebot',
        'wirkung_status': 'in_pruefung',
        'eingabefelder': [],
        'zeigt_dialog': False,
        'schliesst_vorgang': False,
        'sort_order': 20,
        'fx_labels': ['Status „in Prüfung“', 'Wiedervorlage', 'Historie'],
    },
    {
        'code': 'nicht_erreicht',
        'label': 'Nicht erreicht',
        'label_i18n_key': 'sh.erg_nicht_erreicht',
        'kontext': 'kunde_angebot',
        'wirkung_status': '',
        'eingabefelder': [],
        'zeigt_dialog': False,
        'schliesst_vorgang': False,
        'sort_order': 30,
        'fx_labels': ['Erneut anrufen (Kaskade)', 'Historie: Versuch'],
    },
    {
        'code': 'abgelehnt',
        'label': 'Abgelehnt',
        'label_i18n_key': 'sh.erg_abgelehnt',
        'kontext': 'kunde_angebot',
        'wirkung_status': 'verloren',
        'eingabefelder': [{'name': 'grund', 'label': 'Grund', 'typ': 'text'}],
        'zeigt_dialog': True,
        'schliesst_vorgang': True,
        'sort_order': 40,
        'fx_labels': ['Anfrage → verloren', 'Vorgang zu', 'Historie'],
    },
    {
        'code': 'whatsapp_versendet',
        'label': 'Wurde versendet',
        'label_i18n_key': 'sh.erg_wa_versendet',
        'kontext': 'berater_ansprache',
        'wirkung_status': '',
        'eingabefelder': [],
        'zeigt_dialog': False,
        'schliesst_vorgang': True,
        'sort_order': 10,
        'fx_labels': ['Historie: WhatsApp'],
    },
    {
        'code': 'erledigt',
        'label': 'Erledigt',
        'label_i18n_key': 'sh.erg_erledigt',
        'kontext': 'intern',
        'wirkung_status': '',
        'eingabefelder': [],
        'zeigt_dialog': False,
        'schliesst_vorgang': True,
        'sort_order': 10,
        'fx_labels': ['Historie-Eintrag'],
    },
    {
        'code': 'vertrag_eingegangen',
        'label': 'Eingegangen',
        'label_i18n_key': 'sh.erg_vertrag_ok',
        'kontext': 'vertrag',
        'wirkung_status': 'vertrag_eingegangen',
        'eingabefelder': [],
        'zeigt_dialog': False,
        'schliesst_vorgang': True,
        'sort_order': 10,
        'fx_labels': ['Vertrag eingegangen', 'Vorgang abgeschlossen'],
    },
    {
        'code': 'vertrag_nachfassen',
        'label': 'Nicht da — nachfassen',
        'label_i18n_key': 'sh.erg_vertrag_nachfassen',
        'kontext': 'vertrag',
        'wirkung_status': '',
        'eingabefelder': [],
        'zeigt_dialog': False,
        'schliesst_vorgang': False,
        'sort_order': 20,
        'fx_labels': ['Anruf Vertragsklärung'],
    },
    {
        'code': 'snooze',
        'label': 'Später (+1 Tag)',
        'label_i18n_key': 'sh.erg_snooze',
        'kontext': 'wiedervorlage',
        'wirkung_status': '',
        'eingabefelder': [],
        'zeigt_dialog': False,
        'schliesst_vorgang': False,
        'sort_order': 90,
        'fx_labels': ['Fälligkeit +1 Tag'],
    },
    {
        'code': 'verworfen',
        'label': 'Verworfen',
        'label_i18n_key': 'sh.erg_verworfen',
        'kontext': 'intern',
        'wirkung_status': '',
        'eingabefelder': [],
        'zeigt_dialog': False,
        'schliesst_vorgang': True,
        'sort_order': 100,
        'fx_labels': ['geschlossen'],
    },
]

# Default-Regeln (minimal) — Schritte erzeugen Folgeaufgaben
PROZESS_REGELN = [
    {
        'name': 'Nach Angebot: Vertrag vorbereiten',
        'beschreibung': 'Wenn Angebot angenommen → Aufgabe Vertrag erstellen',
        'ausloeser_typ': 'ergebnis',
        'ausloeser_wert': 'angebot_angenommen',
        'schritte': [
            {
                'reihenfolge': 1,
                'aktion_art': 'aufgabe_erzeugen',
                'parameter': {
                    'art': 'dokument',
                    'titel': 'Vertrag erstellen',
                    'frist_offset': '+2d',
                    'prioritaet': 2,
                },
                'frist_offset': '+2d',
            },
        ],
    },
    {
        'name': 'Vertrag fehlt: Anruf',
        'beschreibung': 'Wenn Vertrag nicht da → Anruf-Aufgabe',
        'ausloeser_typ': 'ergebnis',
        'ausloeser_wert': 'vertrag_nachfassen',
        'schritte': [
            {
                'reihenfolge': 1,
                'aktion_art': 'aufgabe_erzeugen',
                'parameter': {
                    'art': 'anruf',
                    'titel': 'Anruf Vertragsklärung',
                    'frist_offset': '+0d',
                    'prioritaet': 1,
                },
                'frist_offset': '+0d',
            },
        ],
    },
]
