# Generated by Django 5.2.9 on 2026-03-11 11:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, help_text='UUID als PRIMARY KEY - Für ES als String konvertieren', primary_key=True, serialize=False)),
                ('entity_id', models.UUIDField(db_column='entity_id', help_text='Referenz auf Entity in abpe_identity App')),
                ('profile_type', models.CharField(choices=[('cv', 'CV / Lebenslauf'), ('company', 'Firmenprofil'), ('project', 'Projektprofil'), ('suite_profile', 'SuiteCRM Profil'), ('unknown', 'Unbekannt')], db_column='profile_type', default='cv', max_length=20)),
                ('origin', models.CharField(choices=[('email', 'Email'), ('namazu', 'Namazu'), ('suitecrm', 'SuiteCRM'), ('upload', 'Upload'), ('unknown', 'Unbekannt')], db_column='origin', default='unknown', max_length=50)),
                ('source', models.CharField(db_column='source', default='unknown', help_text='Zusätzliche Quelle-Information (in DB vorhanden)', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('active', 'Aktiv'), ('archived', 'Archiviert'), ('deleted', 'Gelöscht')], db_column='status', default='draft', max_length=20)),
                ('version', models.IntegerField(db_column='version', default=1, help_text='Interne Version (in DB vorhanden)')),
                ('current_version', models.IntegerField(db_column='current_version', default=1)),
                ('is_current', models.BooleanField(db_column='is_current', default=True, help_text='Ist dies die aktuelle Version?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'abpe_profile_profile',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_id'], name='abpe_profil_entity__e66def_idx'), models.Index(fields=['profile_type'], name='abpe_profil_profile_a6575f_idx'), models.Index(fields=['origin'], name='abpe_profil_origin_41906b_idx'), models.Index(fields=['status'], name='abpe_profil_status_ea09c7_idx'), models.Index(fields=['created_at'], name='abpe_profil_created_43a84c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIDRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aid', models.CharField(db_index=True, help_text='Format: AID-[initials]_[role].[landscape].[experience].[index]', max_length=50, unique=True, verbose_name='AID')),
                ('initials', models.CharField(db_index=True, help_text="Erster Buchstabe Vorname + erster Buchstabe Nachname (z.B. 'jm' für Jan Mustermann)", max_length=10, verbose_name='Initialen')),
                ('role_code', models.IntegerField(choices=[(1, 'Administrator'), (2, 'Entwickler'), (3, 'Technischer Architekt'), (4, 'Projektleiter (IT Organisatorisch)'), (5, 'Sonstiges')], db_index=True, verbose_name='Rolle')),
                ('landscape_code', models.IntegerField(choices=[(1, 'Client Server (Windows/Unix)'), (2, 'Host/Mainframe'), (3, 'Web-Themen'), (4, 'Allround'), (5, 'Sonstiges')], db_index=True, verbose_name='Technologie-Umfeld')),
                ('experience_level', models.IntegerField(choices=[(1, 'Junior (<5 Jahre)'), (2, 'Senior (5-10 Jahre)'), (3, 'Experte (10-15 Jahre)'), (4, 'Senior Experte (>15 Jahre)'), (5, 'Sonstiges (Uni-Abschluss etc.)')], db_index=True, verbose_name='Erfahrungslevel')),
                ('duplicate_index', models.IntegerField(default=1, help_text='Laufende Nummer bei gleicher Klassifikation', verbose_name='Dublettenindex')),
                ('entity_id', models.UUIDField(db_index=True, help_text='Referenz auf abpe_identity_entity')),
                ('years_experience', models.IntegerField(blank=True, help_text='Exakte Jahre für feinere Abstufung', null=True, verbose_name='Jahre Berufserfahrung')),
                ('role_name', models.CharField(blank=True, help_text='Textuelle Beschreibung der Rolle', max_length=100, verbose_name='Rollenname')),
                ('landscape_name', models.CharField(blank=True, help_text='Textuelle Beschreibung des Technologie-Umfelds', max_length=100, verbose_name='Umfeldname')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aid_entries', to='abpe_profile.profile')),
            ],
            options={
                'verbose_name': 'AID Registry',
                'verbose_name_plural': 'AID Registry',
                'db_table': 'abpe_profile_aidregistry',
                'ordering': ['aid'],
                'indexes': [models.Index(fields=['aid'], name='abpe_profil_aid_83fc41_idx'), models.Index(fields=['initials', 'role_code'], name='abpe_profil_initial_a618fa_idx'), models.Index(fields=['profile'], name='abpe_profil_profile_c0b6fc_idx'), models.Index(fields=['entity_id'], name='abpe_profil_entity__3832e3_idx'), models.Index(fields=['years_experience'], name='abpe_profil_years_e_b6e795_idx')],
                'unique_together': {('initials', 'role_code', 'landscape_code', 'experience_level', 'duplicate_index')},
            },
        ),
        migrations.CreateModel(
            name='ProfileVersion',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, help_text='UUID als PRIMARY KEY - Für ES als String konvertieren', primary_key=True, serialize=False)),
                ('version', models.IntegerField(db_column='version')),
                ('data', models.JSONField(db_column='data', help_text='Versionierte Profil-Daten als JSON - Enthält CV-JSON-Schema v2')),
                ('is_current', models.BooleanField(db_column='is_current', default=False, help_text='Ist dies die aktuelle Version?')),
                ('derived_from', models.IntegerField(blank=True, db_column='derived_from', help_text='Von welcher Version abgeleitet?', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('profile', models.ForeignKey(db_column='profile_id', help_text='Referenz zum übergeordneten Profile', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='abpe_profile.profile')),
            ],
            options={
                'verbose_name': 'Profile Version',
                'verbose_name_plural': 'Profile Versions',
                'db_table': 'abpe_profile_profileversion',
                'ordering': ['-version'],
                'indexes': [models.Index(fields=['profile', 'version'], name='abpe_profil_profile_041c50_idx'), models.Index(fields=['is_current'], name='abpe_profil_is_curr_76cebb_idx'), models.Index(fields=['created_at'], name='abpe_profil_created_f155de_idx')],
                'unique_together': {('profile', 'version')},
            },
        ),
    ]
