# Generated by Django 5.2.9 on 2026-08-04 10:03
# Live-applied on ucs5 (migrate OK). Reconstructed into repo after Sync --delete
# removed the live file — verify with: makemigrations abpe_shaduler --dry-run

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abpe_matching_workflow', '0001_initial'),
        ('cv_extractor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RadarItemGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merkmal_hash', models.CharField(db_index=True, max_length=64)),
                ('titel_norm', models.CharField(max_length=250)),
                ('anbieter_anzahl', models.PositiveIntegerField(default=1)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Radar-Gruppe',
                'verbose_name_plural': 'Radar-Gruppen',
            },
        ),
        migrations.CreateModel(
            name='RadarSource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('typ', models.CharField(choices=[('rss', 'RSS'), ('email_alert', 'E-Mail-Alert'), ('html_public', 'HTML öffentlich'), ('manuell', 'Manuell')], max_length=20)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('query', models.CharField(blank=True, max_length=200)),
                ('ziel', models.CharField(choices=[('anfragen', 'Anfragen'), ('berater', 'Berater')], max_length=20)),
                ('intervall_min', models.PositiveIntegerField(default=5)),
                ('aktiv', models.BooleanField(default=True)),
                ('letzter_lauf', models.DateTimeField(blank=True, null=True)),
                ('letzter_status', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'Radar-Quelle',
                'verbose_name_plural': 'Radar-Quellen',
            },
        ),
        migrations.CreateModel(
            name='ProzessRegel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('beschreibung', models.TextField(blank=True)),
                ('aktiv', models.BooleanField(default=True)),
                ('ausloeser_typ', models.CharField(choices=[('status_wechsel', 'Status-Wechsel'), ('ergebnis', 'Ergebnis'), ('zeit_ohne_reaktion', 'Zeit ohne Reaktion'), ('radar_score', 'Radar-Score'), ('manuell', 'Manuell')], max_length=30)),
                ('ausloeser_wert', models.CharField(blank=True, max_length=60)),
                ('bedingung', models.JSONField(blank=True, default=dict)),
                ('erstellt_von', models.CharField(default='user', max_length=20)),
                ('followup_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shaduler_regeln', to='abpe_matching_workflow.followuprule')),
            ],
            options={
                'verbose_name': 'Prozess-Regel',
                'verbose_name_plural': 'Prozess-Regeln',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ErgebnisTyp',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('label_i18n_key', models.CharField(blank=True, max_length=60)),
                ('kontext', models.CharField(db_index=True, max_length=30)),
                ('wirkung_status', models.CharField(blank=True, max_length=30)),
                ('eingabefelder', models.JSONField(blank=True, default=list)),
                ('zeigt_dialog', models.BooleanField(default=False)),
                ('schliesst_vorgang', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('aktiv', models.BooleanField(default=True)),
                ('wirkung_regel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ergebnis_typen', to='abpe_shaduler.prozessregel')),
            ],
            options={
                'verbose_name': 'Ergebnis-Typ',
                'verbose_name_plural': 'Ergebnis-Typen',
                'ordering': ['kontext', 'sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='RadarItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_url', models.CharField(blank=True, max_length=600)),
                ('dedup_hash', models.CharField(db_index=True, max_length=64)),
                ('headline', models.CharField(max_length=250)),
                ('beschreibung', models.TextField(blank=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('eckdaten', models.JSONField(blank=True, default=dict)),
                ('quick_score', models.FloatField(blank=True, null=True)),
                ('top_berater', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('neu', 'Neu'), ('interessant', 'Interessant'), ('uebernommen', 'Übernommen'), ('verworfen', 'Verworfen'), ('gesperrt', 'Gesperrt')], db_index=True, default='neu', max_length=20)),
                ('eingegangen_am', models.DateTimeField(auto_now_add=True)),
                ('project_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radar_items', to='abpe_matching_workflow.projectrequest')),
                ('gruppe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='abpe_shaduler.radaritemgroup')),
                ('quelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='abpe_shaduler.radarsource')),
            ],
            options={
                'verbose_name': 'Radar-Anfrage',
                'verbose_name_plural': 'Radar-Anfragen',
                'ordering': ['-eingegangen_am'],
            },
        ),
        migrations.CreateModel(
            name='RadarConsultantItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profil_url', models.CharField(blank=True, max_length=600)),
                ('dedup_hash', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('verfuegbar_ab', models.DateField(blank=True, null=True)),
                ('satz', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ort', models.CharField(blank=True, max_length=120)),
                ('match_status', models.CharField(choices=[('bekannt', 'Bekannt'), ('unsicher', 'Unsicher'), ('unbekannt', 'Unbekannt')], db_index=True, default='unbekannt', max_length=20)),
                ('match_confidence', models.FloatField(blank=True, null=True)),
                ('vorschlag', models.JSONField(blank=True, default=dict)),
                ('auto_update_log', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('neu', 'Neu'), ('bestaetigt', 'Bestätigt'), ('beobachten', 'Beobachten'), ('verworfen', 'Verworfen')], db_index=True, default='neu', max_length=20)),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radar_items', to='cv_extractor.consultant')),
                ('quelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_items', to='abpe_shaduler.radarsource')),
            ],
            options={
                'verbose_name': 'Radar-Berater',
                'verbose_name_plural': 'Radar-Berater',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Sperrliste',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firma_name', models.CharField(max_length=200)),
                ('firma_name_norm', models.CharField(blank=True, db_index=True, max_length=200)),
                ('crm_account_id', models.CharField(blank=True, db_index=True, max_length=36)),
                ('richtung', models.CharField(choices=[('die_nicht_mit_uns', 'Die nicht mit uns'), ('wir_nicht_mit_denen', 'Wir nicht mit denen'), ('beide', 'Beide')], max_length=30)),
                ('grund', models.TextField(blank=True)),
                ('seit', models.DateField()),
                ('aktiv', models.BooleanField(default=True)),
                ('angelegt_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shaduler_sperren', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sperrliste-Eintrag',
                'verbose_name_plural': 'Sperrliste',
            },
        ),
        migrations.CreateModel(
            name='Aktivitaet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zeitpunkt', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('medium', models.CharField(choices=[('telefon', 'Telefon'), ('email', 'E-Mail'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('dokument', 'Dokument'), ('post', 'Post'), ('termin', 'Termin'), ('system', 'System'), ('radar', 'Radar')], max_length=20)),
                ('titel', models.CharField(max_length=250)),
                ('ref_type', models.CharField(blank=True, db_index=True, max_length=20)),
                ('ref_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('deeplink_url', models.CharField(blank=True, max_length=500)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shaduler_aktivitaeten', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aktivität',
                'verbose_name_plural': 'Aktivitäten',
                'ordering': ['-zeitpunkt'],
                'indexes': [models.Index(fields=['ref_type', 'ref_id'], name='abpe_shadul_ref_typ_b8e4f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Aufgabe',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('art', models.CharField(choices=[('anruf', 'Anruf'), ('termin', 'Termin'), ('email', 'E-Mail'), ('sms_messenger', 'SMS / Messenger'), ('dokument', 'Dokument'), ('post', 'Post'), ('wiedervorlage', 'Wiedervorlage'), ('intern', 'Intern')], db_index=True, max_length=20)),
                ('kanal', models.CharField(blank=True, max_length=20)),
                ('titel', models.CharField(max_length=200)),
                ('beschreibung', models.TextField(blank=True)),
                ('faellig_am', models.DateField(db_index=True)),
                ('faellig_zeit', models.TimeField(blank=True, null=True)),
                ('prioritaet', models.PositiveSmallIntegerField(default=3)),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('erledigt', 'Erledigt'), ('verworfen', 'Verworfen'), ('delegiert', 'Delegiert')], db_index=True, default='offen', max_length=15)),
                ('ref_type', models.CharField(blank=True, db_index=True, max_length=20)),
                ('ref_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('quelle', models.CharField(choices=[('regel', 'Regel'), ('status', 'Status'), ('manuell', 'Manuell'), ('ki', 'KI'), ('radar', 'Radar'), ('mail', 'Mail')], default='manuell', max_length=15)),
                ('ergebnis_daten', models.JSONField(blank=True, default=dict)),
                ('erledigt_am', models.DateTimeField(blank=True, null=True)),
                ('gruppe_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('erledigt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shaduler_erledigt', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kinder', to='abpe_shaduler.aufgabe')),
                ('zugewiesen_an', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shaduler_aufgaben', to=settings.AUTH_USER_MODEL)),
                ('ergebnis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aufgaben', to='abpe_shaduler.ergebnistyp')),
                ('regel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aufgaben', to='abpe_shaduler.prozessregel')),
            ],
            options={
                'verbose_name': 'Aufgabe',
                'verbose_name_plural': 'Aufgaben',
                'ordering': ['faellig_am', 'prioritaet', 'titel'],
                'indexes': [models.Index(fields=['status', 'faellig_am'], name='abpe_shadul_status_26e8ea_idx'), models.Index(fields=['zugewiesen_an', 'status'], name='abpe_shadul_zugewie_4ad759_idx'), models.Index(fields=['ref_type', 'ref_id'], name='abpe_shadul_ref_typ_5a5e3d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProzessSchritt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reihenfolge', models.PositiveIntegerField(default=1)),
                ('aktion_art', models.CharField(choices=[('aufgabe_erzeugen', 'Aufgabe erzeugen'), ('email_senden', 'E-Mail senden'), ('whatsapp_vorbereiten', 'WhatsApp vorbereiten'), ('status_setzen', 'Status setzen'), ('warten', 'Warten')], max_length=30)),
                ('parameter', models.JSONField(blank=True, default=dict)),
                ('frist_offset', models.CharField(blank=True, max_length=10)),
                ('abbruch_bei', models.CharField(blank=True, max_length=30)),
                ('regel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schritte', to='abpe_shaduler.prozessregel')),
            ],
            options={
                'verbose_name': 'Prozess-Schritt',
                'verbose_name_plural': 'Prozess-Schritte',
                'ordering': ['regel', 'reihenfolge'],
                'unique_together': {('regel', 'reihenfolge')},
            },
        ),
    ]
