# Generated by Django 5.2.9 on 2026-05-15 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Hell'), ('dark', 'Dunkel'), ('system', 'System folgen')], default='system', max_length=10, verbose_name='Theme')),
                ('language', models.CharField(choices=[('de', 'Deutsch'), ('en', 'English')], default='de', max_length=5, verbose_name='Sprache')),
                ('sidebar_collapsed', models.BooleanField(default=False, verbose_name='Sidebar eingeklappt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ui_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Benutzereinstellungen',
                'verbose_name_plural': 'Benutzereinstellungen',
            },
        ),
    ]
