# Generated by Django 5.2.9 on 2026-05-16 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_profile', '0002_alter_aidregistry_options_alter_profile_options_and_more'),
        ('abpe_ui', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeraterProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aktiv', 'Aktiv'), ('inaktiv', 'Inaktiv'), ('gesperrt', 'Gesperrt'), ('in_pruefung', 'In Prüfung')], default='in_pruefung', max_length=20, verbose_name='Status')),
                ('ist_externer_berater', models.BooleanField(default=True, help_text='Berater der sich über abcona.de registriert hat', verbose_name='Externer Berater (Homepage)')),
                ('interne_notizen', models.TextField(blank=True, verbose_name='Interne Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('betreuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='betreute_berater', to=settings.AUTH_USER_MODEL, verbose_name='Betreuer')),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='berater_profil', to='abpe_profile.profile', verbose_name='Profil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='berater_profil', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Beraterprofil',
                'verbose_name_plural': 'Beraterprofile',
                'ordering': ['-created_at'],
            },
        ),
    ]
