# Generated by Django 5.2.9 on 2026-05-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_ui', '0002_add_beraterprofil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='nav_order',
            field=models.JSONField(blank=True, default=list, verbose_name='Navigations-Reihenfolge'),
        ),
    ]
