# Generated by Django 5.2.9 on 2026-05-17 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_ui', '0004_add_user_module_permission'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(max_length=100)),
                ('denied', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='auth.group')),
            ],
            options={
                'verbose_name': 'Gruppen Modul-Berechtigung',
                'verbose_name_plural': 'Gruppen Modul-Berechtigungen',
                'unique_together': {('group', 'module_id')},
            },
        ),
    ]
