# Generated by Django 5.2.9 on 2026-05-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_ui', '0005_add_group_module_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='phone_display_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Anzeigename'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='phone_enabled',
            field=models.BooleanField(default=False, verbose_name='Telefon aktiv'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='phone_extension',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Durchwahl'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='phone_pin',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Asterisk PIN'),
        ),
    ]
