# Generated by Django 5.2.9 on 2026-05-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_ui', '0006_add_phone_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='phone_context',
            field=models.CharField(blank=True, default='from-internal', max_length=50, verbose_name='Asterisk Context'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='phone_int_prefix',
            field=models.CharField(blank=True, default='00', max_length=5, verbose_name='Intl. Prefix (+ Ersatz)'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='phone_pre',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Amtsvorwahl Prefix'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='phone_timeout',
            field=models.IntegerField(default=10, verbose_name='Timeout (Sek)'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='phone_webdial_url',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Webdial URL'),
        ),
    ]
