# Generated by Django 5.2.9 on 2026-05-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_matching_workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='open_positions',
            field=models.PositiveIntegerField(default=1, help_text='Anzahl gesuchter Berater'),
        ),
    ]
