# Generated by Django 5.2.9 on 2026-05-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_matching_workflow', '0002_add_open_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectconsultant',
            name='client_contract_channel',
            field=models.CharField(blank=True, choices=[('email', 'E-Mail'), ('post', 'Post'), ('fax', 'Fax'), ('portal', 'Portal'), ('other', 'Sonstiges')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='projectconsultant',
            name='client_contract_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='projectconsultant',
            name='client_contract_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectconsultant',
            name='client_contract_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
