# Generated by Django 5.2.9 on 2026-05-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_matching_workflow', '0003_add_client_contract_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectconsultant',
            name='client_contract_sender',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
