# Generated by Django 5.2.9 on 2026-07-04 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('owner_app', models.CharField(db_index=True, max_length=64, verbose_name='Aufrufende App')),
                ('owner_type', models.CharField(db_index=True, max_length=64, verbose_name='Fachlicher Typ')),
                ('owner_ref', models.CharField(db_index=True, max_length=128, verbose_name='Referenz-ID der App')),
                ('job_key', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Job-Key (idempotent)')),
                ('schedule_type', models.CharField(choices=[('ONCE', 'Einmalig'), ('RECURRING', 'Wiederkehrend (RRULE)')], max_length=12, verbose_name='Typ')),
                ('run_at', models.DateTimeField(blank=True, null=True, verbose_name='Zeitpunkt (bei Einmalig)')),
                ('rrule_string', models.CharField(blank=True, max_length=255, verbose_name='RRULE (bei Wiederkehrend)')),
                ('dtstart', models.DateTimeField(blank=True, null=True, verbose_name='Start der Wiederholung')),
                ('until', models.DateTimeField(blank=True, null=True, verbose_name='Ende der Wiederholung (optional)')),
                ('timezone', models.CharField(default='Europe/Berlin', max_length=64, verbose_name='Zeitzone')),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Naechste Ausfuehrung')),
                ('delivery_mode', models.CharField(choices=[('PUSH', 'Push (Callback-URL)'), ('PULL', 'Pull (App holt selbst ab)')], default='PUSH', max_length=4, verbose_name='Zustellart')),
                ('callback_url', models.URLField(blank=True, max_length=500, verbose_name='Callback-URL (bei Push)')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('lock_key', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Lock-Key')),
                ('max_retries', models.IntegerField(default=3, verbose_name='Max. Wiederholungen')),
                ('retry_backoff_seconds', models.IntegerField(default=300, verbose_name='Retry-Backoff (Sekunden)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktiv'), ('PAUSED', 'Pausiert'), ('CANCELLED', 'Abgebrochen'), ('COMPLETED', 'Abgeschlossen')], db_index=True, default='ACTIVE', max_length=12, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Scheduler-Job',
                'verbose_name_plural': 'Scheduler-Jobs',
                'ordering': ['next_run_at'],
                'indexes': [models.Index(fields=['status', 'next_run_at'], name='abpe_schedu_status_3c6a5a_idx'), models.Index(fields=['owner_app', 'owner_type', 'owner_ref'], name='abpe_schedu_owner_a_e3857f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('job_key', ''), _negated=True), fields=('owner_app', 'owner_type', 'owner_ref', 'job_key'), name='uniq_scheduler_job_key')],
            },
        ),
        migrations.CreateModel(
            name='SchedulerJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('scheduled_for', models.DateTimeField(verbose_name='Geplant fuer')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Gestartet am')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Beendet am')),
                ('status', models.CharField(choices=[('PENDING', 'Ausstehend'), ('RUNNING', 'Laeuft'), ('SUCCESS', 'Erfolgreich'), ('FAILED', 'Fehlgeschlagen'), ('SKIPPED', 'Uebersprungen')], db_index=True, default='PENDING', max_length=12, verbose_name='Status')),
                ('attempt', models.IntegerField(default=1, verbose_name='Versuch')),
                ('leased_at', models.DateTimeField(blank=True, null=True, verbose_name='Abgeholt am (Pull)')),
                ('leased_until', models.DateTimeField(blank=True, null=True, verbose_name='Lease gueltig bis')),
                ('response_status', models.IntegerField(blank=True, null=True, verbose_name='HTTP-Status Antwort')),
                ('response_body', models.TextField(blank=True, verbose_name='Antwort (gekuerzt)')),
                ('error_message', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='abpe_scheduler.schedulerjob', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Job-Ausfuehrung',
                'verbose_name_plural': 'Job-Ausfuehrungen',
                'ordering': ['-scheduled_for'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='abpe_schedu_status_90e3ae_idx')],
                'constraints': [models.UniqueConstraint(fields=('job', 'scheduled_for'), name='uniq_job_run_per_schedule')],
            },
        ),
    ]
