# Generated by Django 5.2.9 on 2026-06-04 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmContactIM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('signal', 'Signal'), ('telegram', 'Telegram'), ('teams', 'MS Teams'), ('skype', 'Skype'), ('slack', 'Slack'), ('sonstiges', 'Sonstiges')], default='whatsapp', max_length=20)),
                ('wert', models.CharField(max_length=255)),
                ('sort', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='im_contacts', to='abpe_crm.crmcontact', to_field='crm_id')),
            ],
            options={
                'verbose_name': 'Messenger',
                'verbose_name_plural': 'Messenger',
                'ordering': ['sort', 'typ'],
            },
        ),
        migrations.CreateModel(
            name='CrmContactPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('mobil', 'Mobil'), ('buero', 'Büro'), ('privat', 'Privat'), ('fax', 'Fax'), ('sonstiges', 'Sonstiges')], default='mobil', max_length=20)),
                ('nummer', models.CharField(max_length=100)),
                ('sort', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='abpe_crm.crmcontact', to_field='crm_id')),
            ],
            options={
                'verbose_name': 'Telefonnummer',
                'verbose_name_plural': 'Telefonnummern',
                'ordering': ['sort', 'typ'],
            },
        ),
        migrations.CreateModel(
            name='CrmContactWebProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('xing', 'Xing'), ('linkedin', 'LinkedIn'), ('gulp', 'Gulp'), ('freelancermap', 'Freelancermap'), ('homepage', 'Homepage'), ('github', 'GitHub'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('kununu', 'Kununu'), ('experteer', 'Experteer'), ('sonstiges', 'Sonstiges')], default='sonstiges', max_length=50)),
                ('url', models.CharField(max_length=1024)),
                ('sort', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_profiles', to='abpe_crm.crmcontact', to_field='crm_id')),
            ],
            options={
                'verbose_name': 'Web-Profil',
                'verbose_name_plural': 'Web-Profile',
                'ordering': ['sort', 'typ'],
            },
        ),
    ]
