# Generated by Django 5.2.9 on 2026-06-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_crm', '0004_remove_crmcontactphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcontactcstm',
            name='einsatzort_plz_c',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='crmcontactcstm',
            name='einsatzort_region_c',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crmcontactcstm',
            name='einsatzort_stadt_c',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
