# Generated by Django 5.2.9 on 2026-06-10 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_crm', '0005_add_einsatzort_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_raw', models.CharField(max_length=100)),
                ('phone_norm', models.CharField(blank=True, db_index=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telefonnummer',
                'verbose_name_plural': 'Telefonnummern',
            },
        ),
        migrations.CreateModel(
            name='CrmPhoneBeanRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bean_id', models.CharField(db_index=True, max_length=36)),
                ('bean_module', models.CharField(max_length=20)),
                ('field_name', models.CharField(max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bean_relations', to='abpe_crm.crmphonenumber')),
            ],
            options={
                'verbose_name': 'Telefon Bean Relation',
                'verbose_name_plural': 'Telefon Bean Relationen',
                'indexes': [models.Index(fields=['bean_id', 'bean_module'], name='abpe_crm_cr_bean_id_268f45_idx')],
                'unique_together': {('bean_id', 'bean_module', 'field_name')},
            },
        ),
    ]
