# Generated by Django 5.2.9 on 2026-06-10 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_crm', '0006_add_phone_bean_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmaccount',
            name='phone_alternate',
        ),
        migrations.RemoveField(
            model_name='crmaccount',
            name='phone_fax',
        ),
        migrations.RemoveField(
            model_name='crmaccount',
            name='phone_office',
        ),
        migrations.RemoveField(
            model_name='crmcontact',
            name='phone_fax',
        ),
        migrations.RemoveField(
            model_name='crmcontact',
            name='phone_home',
        ),
        migrations.RemoveField(
            model_name='crmcontact',
            name='phone_mobile',
        ),
        migrations.RemoveField(
            model_name='crmcontact',
            name='phone_other',
        ),
        migrations.RemoveField(
            model_name='crmcontact',
            name='phone_work',
        ),
    ]
