# Generated by Django 5.2.9 on 2026-06-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_crm', '0007_remove_phone_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmphonebeanrel',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
