# Generated by Django 5.2.9 on 2026-06-10 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_crm', '0008_add_phone_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmUserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='de', max_length=5, verbose_name='Sprache')),
                ('theme', models.CharField(default='light', max_length=10, verbose_name='Theme')),
                ('phone_enabled', models.BooleanField(default=False, verbose_name='Telefon aktiv')),
                ('phone_extension', models.CharField(blank=True, default='', max_length=20, verbose_name='Durchwahl')),
                ('phone_pin', models.CharField(blank=True, default='', max_length=20, verbose_name='PIN')),
                ('phone_display_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Anzeigename')),
                ('phone_webdial_url', models.CharField(blank=True, default='http://172.20.3.120/cgi-bin/webdial.cgi', max_length=200, verbose_name='Webdial URL')),
                ('phone_context', models.CharField(blank=True, default='from-internal', max_length=50, verbose_name='Asterisk Context')),
                ('phone_timeout', models.IntegerField(default=10, verbose_name='Timeout (Sek)')),
                ('phone_int_prefix', models.CharField(blank=True, default='00', max_length=5, verbose_name='Intl. Prefix')),
                ('phone_pre', models.CharField(blank=True, default='', max_length=5, verbose_name='Amtsvorwahl Prefix')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_settings', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'CRM Benutzereinstellungen',
                'verbose_name_plural': 'CRM Benutzereinstellungen',
            },
        ),
    ]
