# Generated by Django 5.2.9 on 2026-06-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_crm', '0009_crm_user_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmusersettings',
            name='softphone_ws',
            field=models.CharField(blank=True, default='wss://pbx.win.abcona.info:8089/ws', max_length=200, verbose_name='Softphone WebSocket URL'),
        ),
    ]
