# Generated by Django 5.2.9 on 2026-06-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_crm', '0010_crmusersettings_softphone_ws'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmusersettings',
            name='softphone_dnd_ext',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='DND Nebenstelle'),
        ),
        migrations.AddField(
            model_name='crmusersettings',
            name='softphone_fwd_target',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Weiterleitungsziel'),
        ),
        migrations.AddField(
            model_name='crmusersettings',
            name='softphone_speed_dials',
            field=models.JSONField(blank=True, default=list, verbose_name='Schnellwahltasten'),
        ),
        migrations.AddField(
            model_name='crmusersettings',
            name='softphone_status_exts',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Überwachte Extensions'),
        ),
        migrations.AddField(
            model_name='crmusersettings',
            name='softphone_vm_ext',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Voicemail Nebenstelle'),
        ),
    ]
