# Generated by Django 5.2.9 on 2026-06-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_crm', '0011_softphone_settings_extend'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmCdr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calldate', models.DateTimeField(db_index=True)),
                ('clid', models.CharField(blank=True, default='', max_length=80)),
                ('src', models.CharField(blank=True, default='', max_length=80)),
                ('dst', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('dcontext', models.CharField(blank=True, default='', max_length=80)),
                ('channel', models.CharField(blank=True, default='', max_length=80)),
                ('dstchannel', models.CharField(blank=True, default='', max_length=80)),
                ('lastapp', models.CharField(blank=True, default='', max_length=80)),
                ('lastdata', models.CharField(blank=True, default='', max_length=80)),
                ('duration', models.IntegerField(default=0)),
                ('billsec', models.IntegerField(default=0)),
                ('disposition', models.CharField(blank=True, db_index=True, default='', max_length=45)),
                ('amaflags', models.IntegerField(default=0)),
                ('accountcode', models.CharField(blank=True, default='', max_length=20)),
                ('uniqueid', models.CharField(db_index=True, max_length=32, unique=True)),
                ('userfield', models.CharField(blank=True, default='', max_length=255)),
                ('did', models.CharField(blank=True, default='', max_length=50)),
                ('recordingfile', models.CharField(blank=True, default='', max_length=255)),
                ('cnum', models.CharField(blank=True, default='', max_length=80)),
                ('cnam', models.CharField(blank=True, default='', max_length=80)),
                ('outbound_cnum', models.CharField(blank=True, default='', max_length=80)),
                ('outbound_cnam', models.CharField(blank=True, default='', max_length=80)),
                ('dst_cnam', models.CharField(blank=True, default='', max_length=80)),
                ('linkedid', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('peeraccount', models.CharField(blank=True, default='', max_length=80)),
                ('sequence', models.IntegerField(default=0)),
                ('src_norm', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('dst_norm', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('direction', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('ext', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('party_number', models.CharField(blank=True, default='', max_length=30)),
                ('party_crm_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('party_module', models.CharField(blank=True, default='', max_length=10)),
                ('party_name', models.CharField(blank=True, default='', max_length=150)),
                ('match_confidence', models.CharField(blank=True, db_index=True, default='', max_length=12)),
                ('match_candidates', models.JSONField(blank=True, default=list)),
                ('is_system', models.BooleanField(db_index=True, default=False)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CDR-Anruf',
                'verbose_name_plural': 'CDR-Anrufe',
                'ordering': ['-calldate'],
                'indexes': [models.Index(fields=['party_crm_id', '-calldate'], name='abpe_crm_cr_party_c_b3b10c_idx'), models.Index(fields=['ext', '-calldate'], name='abpe_crm_cr_ext_64262b_idx'), models.Index(fields=['linkedid'], name='abpe_crm_cr_linkedi_abcdbe_idx')],
            },
        ),
    ]
