# Generated by Django 5.2.9 on 2026-06-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_crm', '0012_crmcdr'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmExtensionOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(db_index=True, max_length=10, unique=True)),
                ('contact_crm_id', models.CharField(blank=True, max_length=36, null=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Extension-Besitzer',
                'verbose_name_plural': 'Extension-Besitzer',
            },
        ),
        migrations.CreateModel(
            name='CrmCallRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(db_index=True, max_length=255, unique=True)),
                ('pbx_path', models.CharField(max_length=500)),
                ('local_path', models.CharField(blank=True, max_length=500, null=True)),
                ('extension', models.CharField(db_index=True, max_length=10)),
                ('caller_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('contact_crm_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('account_crm_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('is_assigned', models.BooleanField(db_index=True, default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('duration_sec', models.IntegerField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anruf-Aufnahme',
                'verbose_name_plural': 'Anruf-Aufnahmen',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['contact_crm_id'], name='abpe_crm_cr_contact_6baf9f_idx'), models.Index(fields=['account_crm_id'], name='abpe_crm_cr_account_42084d_idx'), models.Index(fields=['is_assigned', 'recorded_at'], name='abpe_crm_cr_is_assi_5c395e_idx')],
            },
        ),
    ]
