# Generated by Django 5.2.9 on 2026-07-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_crm', '0013_crmextensionowner_crmcallrecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcontactnote',
            name='wavnote_mailbox',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='crmcontactnote',
            name='wavnote_msg_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='crmcontactnote',
            name='wavnote_raw_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
