# Generated by Django 5.2.9 on 2026-07-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_crm', '0014_crmcontactnote_wavnote_mailbox_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmWavnoteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox', models.CharField(db_index=True, max_length=10)),
                ('msg_id', models.CharField(max_length=20)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('archived_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'WAV-Notiz Status',
                'verbose_name_plural': 'WAV-Notiz Status',
                'unique_together': {('mailbox', 'msg_id')},
            },
        ),
    ]
