# Generated by Django 5.2.9 on 2026-07-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_crm', '0015_crmwavnotestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmusersettings',
            name='favoriten_berater',
            field=models.JSONField(blank=True, default=list, verbose_name='Favoriten (Berater)'),
        ),
        migrations.AddField(
            model_name='crmusersettings',
            name='favoriten_kunden',
            field=models.JSONField(blank=True, default=list, verbose_name='Favoriten (Kunden)'),
        ),
    ]
