# Generated by Django 5.2.9 on 2026-07-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_crm', '0016_crmusersettings_favoriten_berater_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmusersettings',
            name='timezone',
            field=models.CharField(default='Europe/Berlin', max_length=64, verbose_name='Zeitzone'),
        ),
    ]
