# Generated by Django 5.2.9 on 2026-04-13 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('normalized_name', models.CharField(db_index=True, max_length=200)),
                ('suffix', models.IntegerField(default=0)),
                ('version', models.CharField(default='1.0.0.0', max_length=20)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['normalized_name', 'suffix'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(db_index=True, max_length=50)),
                ('field_name', models.CharField(max_length=100)),
                ('field_label', models.CharField(max_length=200)),
                ('regex_pattern', models.TextField()),
                ('confidence', models.FloatField(default=0.5)),
                ('usage_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('learned_by_ai', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-confidence', '-usage_count'],
            },
        ),
        migrations.CreateModel(
            name='FocusArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('frequency', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('frequency', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('confidence', models.FloatField(default=0.7)),
                ('frequency', models.IntegerField(default=1)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-frequency', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('prompt_text', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['stage'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('category_name', models.CharField(db_index=True, max_length=100)),
                ('frequency', models.IntegerField(default=1)),
                ('confidence', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-frequency', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('example_terms', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(db_index=True, max_length=50, unique=True)),
                ('version', models.CharField(default='1.0.0.0', max_length=20)),
                ('consultant_dir', models.CharField(blank=True, db_index=True, max_length=200)),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, db_index=True, max_length=200)),
                ('headline', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('availability', models.CharField(blank=True, max_length=100)),
                ('edv_experience_since', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='pending', max_length=30)),
                ('error_message', models.TextField(blank=True)),
                ('source_type', models.CharField(default='upload', max_length=50)),
                ('source_filename', models.CharField(blank=True, max_length=500)),
                ('source_filesize', models.IntegerField(default=0)),
                ('source_import_id', models.CharField(blank=True, max_length=100)),
                ('pipeline_version', models.CharField(default='4.0', max_length=20)),
                ('pipeline_step', models.CharField(default='extracted', max_length=50)),
                ('pipeline_extractor', models.CharField(default='cv_extractor', max_length=50)),
                ('pipeline_model', models.CharField(default='qwen2.5:7b', max_length=50)),
                ('pipeline_self_learning', models.BooleanField(default=True)),
                ('duplicate_exists', models.BooleanField(default=False)),
                ('duplicate_message', models.TextField(blank=True)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('master_json_export', models.JSONField(blank=True, default=dict)),
                ('extracted_json_export', models.JSONField(blank=True, default=dict)),
                ('raw_text', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['first_name', 'last_name'], name='cv_extracto_first_n_d13e90_idx'), models.Index(fields=['status', 'location'], name='cv_extracto_status_fa7bd1_idx'), models.Index(fields=['aid', 'version'], name='cv_extracto_aid_a41346_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsultantMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(db_index=True, default=0.0)),
                ('skill_match_score', models.FloatField(db_index=True, default=0.0)),
                ('role_match_score', models.FloatField(db_index=True, default=0.0)),
                ('industry_match_score', models.FloatField(db_index=True, default=0.0)),
                ('skill_weights', models.JSONField(default=dict)),
                ('role_weights', models.JSONField(default=dict)),
                ('industry_weights', models.JSONField(default=dict)),
                ('preferred_roles', models.JSONField(default=list)),
                ('preferred_industries', models.JSONField(default=list)),
                ('preferred_locations', models.JSONField(default=list)),
                ('min_experience_years', models.IntegerField(default=0)),
                ('must_have_skills', models.JSONField(default=list)),
                ('nice_to_have_skills', models.JSONField(default=list)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('calculated_by', models.CharField(default='cv_extractor', max_length=100)),
                ('consultant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matching', to='cv_extractor.consultant')),
            ],
            options={
                'ordering': ['-overall_score'],
            },
        ),
        migrations.CreateModel(
            name='ConsultantStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_experience_years', models.IntegerField(db_index=True, default=0)),
                ('total_months', models.IntegerField(default=0)),
                ('project_count', models.IntegerField(db_index=True, default=0)),
                ('skill_count', models.IntegerField(db_index=True, default=0)),
                ('unique_categories', models.IntegerField(default=0)),
                ('top_skills', models.JSONField(default=list)),
                ('certification_count', models.IntegerField(db_index=True, default=0)),
                ('top_certifications', models.JSONField(default=list)),
                ('placement_probability', models.FloatField(db_index=True, default=0.0)),
                ('market_value_estimate', models.IntegerField(db_index=True, default=0)),
                ('demand_index', models.FloatField(db_index=True, default=0.0)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='cv_extractor.consultant')),
            ],
            options={
                'verbose_name_plural': 'Consultant Statistics',
                'ordering': ['-demand_index', '-placement_probability'],
            },
        ),
        migrations.CreateModel(
            name='ConsultantVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(db_index=True, max_length=50, unique=True)),
                ('consultant_dir', models.CharField(db_index=True, max_length=200)),
                ('version', models.CharField(max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('consultant_dir', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, max_length=200)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('period', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='cv_extractor.consultant')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('company', models.CharField(blank=True, db_index=True, max_length=200)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='cv_extractor.consultant')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_text', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='cv_extractor.experience')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500)),
                ('file_path', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='cv_extracto_status_daebeb_idx'), models.Index(fields=['file_name'], name='cv_extracto_file_na_6689c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExtractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('DEBUG', 'Debug')], default='INFO', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='cv_extractor.extractionjob')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultantFocusArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.5)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_areas', to='cv_extractor.consultant')),
                ('focus_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_extractor.focusarea')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultantIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.5)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industries', to='cv_extractor.consultant')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_extractor.industry')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('issuer_name', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications', to='cv_extractor.issuer')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JsonExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('master', 'Master JSON'), ('pre', 'Pre JSON'), ('full', 'Full CV JSON')], max_length=20)),
                ('json_data', models.JSONField(default=dict)),
                ('version', models.CharField(default='4.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='cv_extractor', max_length=100)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='json_exports', to='cv_extractor.consultant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultantLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, choices=[('A1', 'A1 - Anfänger'), ('A2', 'A2 - Grundlegend'), ('B1', 'B1 - Fortgeschritten'), ('B2', 'B2 - Fließend'), ('C1', 'C1 - Verhandlungssicher'), ('C2', 'C2 - Muttersprache')], max_length=2)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='cv_extractor.consultant')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_extractor.language')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='cv_extractor.experience')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_extractor.skill')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultantSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.5)),
                ('last_used_year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cv_extractor.consultant')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_extractor.skill')),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='cv_extractor.skillcategory'),
        ),
        migrations.CreateModel(
            name='SkillRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_from', models.CharField(db_index=True, max_length=200)),
                ('term_to', models.CharField(db_index=True, max_length=200)),
                ('relation_type', models.CharField(choices=[('synonym', 'Synonym'), ('related', 'Verwandt'), ('specialization', 'Spezialisierung')], default='synonym', max_length=20)),
                ('weight', models.FloatField(default=0.5)),
                ('frequency', models.IntegerField(default=1)),
                ('confidence', models.FloatField(default=0.5)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-weight', '-frequency'],
                'unique_together': {('term_from', 'term_to', 'relation_type')},
            },
        ),
        migrations.CreateModel(
            name='TrainingTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=200, unique=True)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('confidence', models.FloatField(default=0.5)),
                ('frequency', models.IntegerField(default=1)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('is_technology_category', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-frequency', 'term'],
                'indexes': [models.Index(fields=['category'], name='cv_extracto_categor_3e55be_idx'), models.Index(fields=['term'], name='cv_extracto_term_f0b87b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsultantCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_obtained', models.CharField(blank=True, max_length=20)),
                ('expiry_date', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_extractor.certification')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='cv_extractor.consultant')),
            ],
            options={
                'ordering': ['-date_obtained'],
                'unique_together': {('consultant', 'certification')},
            },
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['consultant', 'company'], name='cv_extracto_consult_1c1acd_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['industry'], name='cv_extracto_industr_a5fb9e_idx'),
        ),
        migrations.AddIndex(
            model_name='extractionlog',
            index=models.Index(fields=['job', 'step'], name='cv_extracto_job_id_ac29ed_idx'),
        ),
        migrations.AddIndex(
            model_name='extractionlog',
            index=models.Index(fields=['level'], name='cv_extracto_level_122777_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='consultantfocusarea',
            unique_together={('consultant', 'focus_area')},
        ),
        migrations.AlterUniqueTogether(
            name='consultantindustry',
            unique_together={('consultant', 'industry')},
        ),
        migrations.AddIndex(
            model_name='jsonexport',
            index=models.Index(fields=['consultant', 'export_type'], name='cv_extracto_consult_a43b1d_idx'),
        ),
        migrations.AddIndex(
            model_name='jsonexport',
            index=models.Index(fields=['created_at'], name='cv_extracto_created_b40a82_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='consultantlanguage',
            unique_together={('consultant', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='experiencetechnology',
            unique_together={('experience', 'skill')},
        ),
        migrations.AddIndex(
            model_name='consultantskill',
            index=models.Index(fields=['consultant', 'weight'], name='cv_extracto_consult_bbc7bb_idx'),
        ),
        migrations.AddIndex(
            model_name='consultantskill',
            index=models.Index(fields=['skill', 'weight'], name='cv_extracto_skill_i_372c14_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='consultantskill',
            unique_together={('consultant', 'skill')},
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['category_name', '-frequency'], name='cv_extracto_categor_2eb07a_idx'),
        ),
    ]
