# Generated by Django 5.2.9 on 2026-04-13 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_extractor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant_name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('consultant_aid', models.CharField(blank=True, db_index=True, max_length=50)),
                ('json_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_cv', to='cv_extractor.extractionjob')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['consultant_name'], name='cv_extracto_consult_cefcc0_idx'), models.Index(fields=['consultant_aid'], name='cv_extracto_consult_3bf467_idx')],
            },
        ),
    ]
