# Generated by Django 5.2.9 on 2026-04-14 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_extractor', '0002_add_extracted_cv'),
    ]

    operations = [
    ]
