# Generated by Django 5.2.9 on 2026-04-15 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_extractor', '0003_add_focus_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='consultant',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='consultant',
            name='stand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='consultant',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='target_path',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='FocusExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_experience_items', to='cv_extractor.consultant')),
            ],
            options={
                'verbose_name_plural': 'Focus Experiences',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
