# Generated by Django 5.2.9 on 2026-04-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_extractor', '0004_add_consultant_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='education_type',
            field=models.CharField(choices=[('degree', 'Ausbildung / Studium'), ('course', 'Schulung / Kurs'), ('certification', 'Zertifikatskurs')], db_index=True, default='degree', max_length=20),
        ),
        migrations.AddField(
            model_name='education',
            name='issuer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
