# Generated by Django 5.2.9 on 2026-04-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_extractor', '0005_education_education_type_education_issuer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/cv/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=500)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('target_directory', models.CharField(blank=True, max_length=200)),
                ('target_version', models.CharField(blank=True, max_length=20)),
                ('action_type', models.CharField(default='new', max_length=20)),
                ('status', models.CharField(choices=[('uploaded', 'Hochgeladen'), ('processing', 'Wird verarbeitet'), ('completed', 'Abgeschlossen'), ('failed', 'Fehlgeschlagen')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('aid', models.CharField(blank=True, max_length=50)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('consultant_dir', models.CharField(blank=True, max_length=200)),
                ('task_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
