# Generated by Django 5.2.9 on 2026-04-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_extractor', '0006_uploadedpdf'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='extractedcv',
            name='cv_extracto_consult_cefcc0_idx',
        ),
        migrations.RemoveIndex(
            model_name='extractedcv',
            name='cv_extracto_consult_3bf467_idx',
        ),
        migrations.AddField(
            model_name='uploadedpdf',
            name='consultant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='phone',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='website',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='consultantlanguage',
            name='level',
            field=models.CharField(blank=True, choices=[('A1', 'A1 – Anfaenger'), ('A2', 'A2 – Grundlegend'), ('B1', 'B1 – Fortgeschritten'), ('B2', 'B2 – Fliessend'), ('C1', 'C1 – Verhandlungssicher'), ('C2', 'C2 – Muttersprache')], max_length=2),
        ),
    ]
