# Generated by Django 5.2.9 on 2026-04-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_extractor', '0007_remove_extractedcv_cv_extracto_consult_cefcc0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='degree',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
