# Generated by Django 5.2.9 on 2026-04-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_extractor', '0008_add_degree_to_consultant'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='hourly_rate',
            field=models.IntegerField(blank=True, help_text='Stundensatz in EUR (individuell verhandelbar)', null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='placement_text',
            field=models.CharField(blank=True, default='nach Absprache', help_text='Vermittlungsstatus (z.B. Auf Anfrage, Sehr gefragt)', max_length=100),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='trained_on_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='updated_by',
            field=models.CharField(default='manual', max_length=50),
        ),
        migrations.AddField(
            model_name='trainingterm',
            name='in_prompt',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
