# Generated by Django 5.2.9 on 2026-05-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_extractor', '0009_add_enricher_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='aid_base',
            field=models.CharField(blank=True, db_index=True, help_text='AID des DE-Hauptprofils (nur bei EN-Version gesetzt)', max_length=50),
        ),
        migrations.AddField(
            model_name='consultant',
            name='language',
            field=models.CharField(db_index=True, default='de', help_text="Sprache des Profils: 'de' oder 'en'", max_length=5),
        ),
    ]
