# Generated by Django 5.2.9 on 2026-05-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_extractor', '0010_add_language_aid_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantskill',
            name='category_name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
