# Generated by Django 5.2.9 on 2026-05-05 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_extractor', '0011_add_category_name_to_consultantskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('content_type', models.CharField(blank=True, choices=[('text', 'Freitext'), ('list', 'Liste'), ('table', 'Tabelle'), ('note', 'Notiz'), ('other', 'Sonstiges')], default='text', max_length=100)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_content', to='cv_extractor.consultant')),
            ],
            options={
                'verbose_name_plural': 'Other Contents',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
