# Generated by Django 5.2.9 on 2026-05-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_extractor', '0012_othercontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='show_name',
            field=models.BooleanField(default=False, help_text='Name im HTML anzeigen (True) oder anonymisiert als AID (False)'),
        ),
    ]
