# Generated by Django 5.2.9 on 2026-05-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_extractor', '0013_add_show_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpdf',
            name='from_email',
            field=models.EmailField(blank=True, help_text='Absender-E-Mail (aus ingest_email)', max_length=254),
        ),
    ]
