# Generated by Django 5.2.9 on 2026-05-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_extractor', '0014_add_from_email_to_uploadedpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedpdf',
            name='from_email',
            field=models.EmailField(blank=True, default='', help_text='Absender-E-Mail (aus ingest_email)', max_length=254, null=True),
        ),
    ]
