# Generated by Django 5.2.9 on 2026-07-04 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetmeMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('start_at', models.DateTimeField(verbose_name='Beginn')),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='Dauer (Minuten)')),
                ('room_extension', models.CharField(blank=True, max_length=20, verbose_name='Konferenzraum (Extension)')),
                ('meetme_number', models.CharField(blank=True, max_length=20, verbose_name='MeetMe-Nummer')),
                ('status', models.CharField(choices=[('PLANNED', 'Geplant'), ('CONFIRMED', 'Bestaetigt'), ('CANCELLED', 'Abgesagt'), ('COMPLETED', 'Abgeschlossen')], default='PLANNED', max_length=20, verbose_name='Status')),
                ('account_crm_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Kunde (crm_id)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetme_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetmeGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('contact_crm_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Kontakt (crm_id)')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('status', models.CharField(choices=[('PENDING', 'Ausstehend'), ('CONFIRMED', 'Bestaetigt'), ('DECLINED', 'Abgesagt')], default='PENDING', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv (in Erinnerungen beruecksichtigen)')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='abpe_meetme.meetmemeeting', verbose_name='Meeting')),
            ],
            options={
                'verbose_name': 'Gast',
                'verbose_name_plural': 'Gaeste',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MeetmeReminderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('offset_value', models.IntegerField(verbose_name='Offset-Wert')),
                ('offset_unit', models.CharField(choices=[('MINUTES', 'Minuten'), ('HOURS', 'Stunden'), ('DAYS', 'Tage')], default='HOURS', max_length=10, verbose_name='Einheit')),
                ('time_of_day', models.TimeField(blank=True, null=True, verbose_name='Uhrzeit (nur bei Tage)')),
                ('mode', models.CharField(choices=[('MANUAL', 'Manuell pruefen'), ('AUTO', 'Automatisch senden')], default='MANUAL', max_length=10, verbose_name='Modus')),
                ('send_copy_to_owner', models.BooleanField(default=False, verbose_name='Kopie an Ersteller (nur bei Automatisch)')),
                ('template_id', models.IntegerField(blank=True, null=True, verbose_name='Vorlage (EmailTemplate-ID)')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_rules', to='abpe_meetme.meetmemeeting', verbose_name='Meeting')),
            ],
            options={
                'verbose_name': 'Erinnerungsregel',
                'verbose_name_plural': 'Erinnerungsregeln',
                'ordering': ['meeting', '-offset_value'],
            },
        ),
        migrations.CreateModel(
            name='MeetmeReminderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('scheduled_at', models.DateTimeField(db_index=True, verbose_name='Faellig am')),
                ('status', models.CharField(choices=[('PENDING', 'Ausstehend'), ('DUE', 'Faellig'), ('SENT', 'Gesendet'), ('SKIPPED', 'Uebersprungen'), ('FAILED', 'Fehlgeschlagen')], default='PENDING', max_length=20, verbose_name='Status')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Betreff')),
                ('body', models.TextField(blank=True, verbose_name='Text')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gesendet am')),
                ('failed_reason', models.TextField(blank=True, verbose_name='Fehlergrund')),
                ('email_log_id', models.IntegerField(blank=True, null=True, verbose_name='E-Mail-Log-ID')),
                ('scheduler_job_id', models.IntegerField(blank=True, null=True, verbose_name='Scheduler-Job-ID')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_deliveries', to='abpe_meetme.meetmeguest', verbose_name='Gast')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='abpe_meetme.meetmereminderrule', verbose_name='Regel')),
            ],
            options={
                'verbose_name': 'Erinnerungs-Zustellung',
                'verbose_name_plural': 'Erinnerungs-Zustellungen',
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='abpe_meetme_status_6bc557_idx')],
                'constraints': [models.UniqueConstraint(fields=('rule', 'guest'), name='uniq_meetme_delivery_per_rule_guest')],
            },
        ),
    ]
