# Generated by Django 5.2.9 on 2026-07-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_meetme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetmereminderrule',
            name='is_change_notice',
            field=models.BooleanField(default=False, verbose_name='Terminaenderungs-Hinweis'),
        ),
    ]
