# Generated by Django 5.2.9 on 2026-07-08 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_meetme', '0002_meetmereminderrule_is_change_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetmereminderrule',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_reminder_rules', to='abpe_meetme.meetmeguest', verbose_name='Nur fuer diesen Gast (leer = alle Gaeste)'),
        ),
    ]
