# Generated by Django 5.2.9 on 2026-07-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_meetme', '0003_meetmereminderrule_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetmeguest',
            name='invited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Eingeladen am'),
        ),
    ]
