# Generated by Django 5.2.9 on 2026-07-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpe_meetme', '0005_meetmeguest_notify_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetmereminderrule',
            name='attachment_refs',
            field=models.JSONField(blank=True, default=list, verbose_name='Anhaenge (Referenzen)'),
        ),
        migrations.AddField(
            model_name='meetmereminderrule',
            name='body',
            field=models.TextField(blank=True, verbose_name='Text (individuell)'),
        ),
        migrations.AddField(
            model_name='meetmereminderrule',
            name='subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='Betreff (individuell)'),
        ),
    ]
